# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0005_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(upload_to='media_images/'),
        ),
    ]
